# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: CWVisit_CWSpam.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'CWVisit_CWSpam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x43WVisit_CWSpam.proto\x12\nplayerinfo\"e\n\tBasicInfo\x12\x0b\n\x03UID\x18\x01 \x01(\x03\x12\x16\n\x0ePlayerNickname\x18\x03 \x01(\t\x12\x14\n\x0cPlayerRegion\x18\x05 \x01(\t\x12\x0e\n\x06Levels\x18\x06 \x01(\x03\x12\r\n\x05Likes\x18\x15 \x01(\x03\"2\n\x04Info\x12*\n\x0b\x41\x63\x63ountInfo\x18\x01 \x01(\x0b\x32\x15.playerinfo.BasicInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CWVisit_CWSpam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASICINFO']._serialized_start=36
  _globals['_BASICINFO']._serialized_end=137
  _globals['_INFO']._serialized_start=139
  _globals['_INFO']._serialized_end=189
# @@protoc_insertion_point(module_scope)
